// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_firebase_auth_demo/test/src/screens/register/bloc/register_screen_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_firebase_auth_demo/src/domain/auth_repository.dart'
    as _i5;
import 'package:flutter_firebase_auth_demo/src/domain/entities/registered_account.dart'
    as _i2;
import 'package:flutter_firebase_auth_demo/src/domain/models/registration_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisteredAccount_0 extends _i1.SmartFake
    implements _i2.RegisteredAccount {
  _FakeRegisteredAccount_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i3.RegisterUseCase {
  @override
  _i4.Future<_i2.RegisteredAccount> execute(_i5.AccountCredential? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.RegisteredAccount>.value(_FakeRegisteredAccount_0(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.RegisteredAccount>.value(_FakeRegisteredAccount_0(
          this,
          Invocation.method(
            #execute,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.RegisteredAccount>);
}
